name: Meson

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
#    - name: Checkout submodules
#      run: git submodule update --init --recursive
    
    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list /etc/apt/sources.list.d/*
        printf "Enabled: yes\nTypes: deb\nURIs: http://azure.archive.ubuntu.com/ubuntu/\nSuites: focal focal-updates focal-backports focal-security devel\nComponents: main universe multiverse restricted\n" | sudo tee /etc/apt/sources.list.d/system.sources
        printf "APT::Default-Release \"focal\";\n" | sudo tee /etc/apt/apt.conf.d/00default-release
        sudo apt-get -qq update && sudo apt-get -qq install --assume-yes meson/hirsute libboost-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10

    - name: Configure Meson
      run: meson setup build --buildtype=release

    - name: Build
      run: meson compile -C build

#    - name: Test
#      run: meson test -C build

    - name: Store compiled program
      uses: actions/upload-artifact@v2
      with: 
        name: websocket-chat-backend-main
        path: ${{runner.workspace}}/websocket-chat-backend/build/Websocket-chat
